"""State and schema definitions for the True Multi-Agent Graph Orchestrator."""

from typing import Annotated, Literal
from pydantic import BaseModel, Field
from langchain_core.messages import BaseMessage


class SubTask(BaseModel):
    """An individual sub-task in the multi-agent execution plan."""
    task_id: str = Field(description="Unique ID for this subtask (e.g. task_1, task_2)")
    agent: Literal["sql_analyst", "document_expert", "web_researcher", "direct"] = Field(
        description="The specialized agent responsible for this subtask"
    )
    instruction: str = Field(description="Self-contained actionable instruction for this agent")
    depends_on: list[str] = Field(
        default_factory=list,
        description="IDs of prerequisite tasks that must finish before this task runs (empty for parallel execution)",
    )


class ExecutionPlan(BaseModel):
    """The plan generated by the Smart Router."""
    standalone_query: str = Field(description="The user's query with all pronouns and context resolved")
    is_clarification_needed: bool = Field(
        default=False,
        description="True if the query is too ambiguous to answer without asking user for clarification",
    )
    clarification_question: str = Field(
        default="",
        description="The question to ask the user if clarification is needed",
    )
    is_complex: bool = Field(
        default=False,
        description="True if the query requires multiple agents (either parallel or sequential)",
    )
    subtasks: list[SubTask] = Field(
        default_factory=list,
        description="List of sub-tasks to execute across specialized agents",
    )


class AgentFinding(BaseModel):
    """Findings collected by an individual specialist agent."""
    task_id: str
    agent: str
    status: str = "success"  # "success" | "no_results" | "error"
    content: str
    sources: list[str] = Field(default_factory=list)


class MultiAgentState(BaseModel):
    """Global execution state flowing through the multi-agent graph."""
    messages: list[BaseMessage] = Field(default_factory=list)
    user_id: str = ""
    session_id: str = ""
    include_shared: bool = True
    
    # Router & Plan
    plan: ExecutionPlan | None = None
    
    # Accumulated Findings from Worker Agents
    findings: dict[str, str] = Field(default_factory=dict)
    sources: list[str] = Field(default_factory=list)
    reasoning_trace: list[str] = Field(default_factory=list)
    
    # Final Output
    final_answer: str = ""
